config/routes.rb
Depot::Application.routes.draw do

  devise_for :users

  resources :orders, :only => [:new, :create, :index, :show] do
    put 'ship', :on => :member
  end

  resources :line_items, :only => [:create, :destroy]

  delete 'cart/destroy' => 'carts#destroy'

  resources :products do
    resources :comments, :only => [:new, :create]
    get :who_bought, :on => :member
  end

  get "store" => 'store#index'

  root :to => 'store#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  belongs_to :pay_type
  belongs_to :user

  validates :name, :address, :email, :pay_type, :presence => true

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  
  def ship
    self.ship_date = Time.now
    save
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource

  def new
    @cart = current_cart
    redirect_to store_url, :notice => 'Your cart is empty' if @cart.line_items.empty?
  end

  def create
    @order.add_line_items_from_cart current_cart
    @order.user = current_user if current_user

    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      Notifier.order_received(@order).deliver
      redirect_to store_url, :notice => 'Thank you for your order'
    else
      render :action => :new
    end
  end

  def index
    @orders = @orders.paginate(:page => params[:page], :per_page => 10,
                               :order => 'created_at desc')
  end

  def ship
    if @order.ship
      Notifier.order_shipped(@order).deliver
      redirect_to order_path(@order), :notice => 'The Order marked as shipped'
    end
  end
end

app/views/orders/_form.html.erb
<%= semantic_form_for @order do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :address, :input_html => { :rows => 3 } %>
    <%= f.input :email %>
    <%= f.input :pay_type, :collection => PayType.all,
                :prompt => 'Select a payment method' %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table id="orders">
  <% @orders.each do |order| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td class="name"><%= order.name %></td>
      <td class="address"><%= order.address %></td>
      <td class="email"><%= order.email %></td>
      <td class="pay_type"><%= order.pay_type.name %></td>
      <td class="ship_date"><%= format_time order.ship_date %></td>
      <td class="list_actions">
        <%= link_to 'Show', order %><br/>
      </td>
    </tr>
  <% end %>
</table>

<p><%= will_paginate @orders %></p>

app/views/orders/new.html.erb
<div class="depot_form" >
  <fieldset>
    <legend>Please Enter Your Details</legend>
    <%= render 'form' %>
  </fieldset>
</div>

app/views/orders/show.html.erb
<div id="order">  
  <p>
    <b>Name:</b>
    <%= @order.name %>
  </p>

  <p>
    <b>Address:</b>
    <%= @order.address %>
  </p>
  <p>
    <b>Email:</b>
    <%= @order.email %>
  </p>
  <p>
    <b>Pay type:</b>
    <%= @order.pay_type.name %>
  </p>
  <% if @order.ship_date %>
    <p>
      <b>Ship date:</b>
      <%= format_time @order.ship_date %>
    </p>
  <% end %>

  <table><%= render @order.line_items %></table>
</div>

<% if can?(:ship, @order) && !@order.ship_date %>
  <%= button_to 'Shipped', ship_order_path(@order), :method => :put,
                :confirm => 'Are you sure?' %>
<% end %>

<%= link_to 'Back', orders_path %>