config/routes.rb
Depot::Application.routes.draw do

  devise_for :users

  resources :orders, :only => [:new, :create, :index, :show] do
    put 'ship', :on => :member
  end

  resources :line_items, :only => [:create, :destroy]

  delete 'cart/destroy' => 'carts#destroy'

  resources :products do
    resources :comments, :only => [:new, :create]
    get :who_bought, :on => :member
  end

  get "store" => 'store#index'

  root :to => 'store#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  def add_product(product)
    current_item = line_items.where(:product_id => product.id,
                                    :price => product.price).first
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product.id,
                                      :price => product.price)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_items
    line_items.sum(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def destroy
    current_cart.destroy
    session[:cart_id] = nil
    
    respond_to do |format|
      format.html { redirect_to root_path, 
                                :notice => 'Your cart is currently empty' }
      format.js
    end
  end
end

app/views/carts/_cart.html.erb
<%= hidden_div_if cart.line_items.empty?, :id => 'cart' do %>
  <div class="cart_title">Your cart</div>
  <table>
    <%= render cart.line_items, :with_remove_button => true %>
  
    <tr class="total_line">
      <td colspan="2">Total</td>
      <td class="total_cell"><%= price_for cart.total_price %></td>
    </tr>
  </table>

  <%= button_to 'Checkout', new_order_path, :method => :get,
                            :disabled => @order %>
  <%= button_to 'Empty cart', cart_destroy_path, :method => :delete,
                :confirm => 'Are you sure?', :remote => true %>
<% end %>